### PR TITLE
Feature/segment transcoding

### PR DESCRIPTION
**Pull request by cdglasz**
**Issues:**

- https://github.com/openmpf/openmpf/issues/1543
- https://github.com/openmpf/openmpf/pull/1582
- https://github.com/openmpf/openmpf/issues/1605

**Related PRs:**

- https://github.com/openmpf/openmpf-components/pull/296

---
This change is [Reviewable](https://reviewable.io/reviews/openmpf/openmpf-python-component-sdk/63)

### CODE REVIEW

**Review by brosenberg42 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-python-component-sdk/63)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @cdglasz and @jrobble)

___
*[`detection/component_util/mpf_component_util/audio_transcoder.py` line 118 at r2](https://reviewable.io/reviews/openmpf/openmpf-python-component-sdk/63#-N8xQwNRDABovVjsxoFT:-N8xQwNRDABovVjsxoFU:brtl787) ([raw file](https://github.com/openmpf/openmpf-python-component-sdk/blob/84a0e2fdc5e8c819c97ae9cf13ab0765db475883/detection/component_util/mpf_component_util/audio_transcoder.py#L118)):*
> ```Python
>             if t1 is not None:
>                 tr.append(f"end={t1 / 1000.0:f}")
>             trim_str += f"[0:a]atrim={':'.join(tr)},asetpts=PTS-STARTPTS[a{i}];"
> ```

Strings are immutable so doing the concatenation like this in a loop results in a quadratic runtime. ( https://docs.python.org/3/library/stdtypes.html#:~:text=building%20up%20a%20sequence%20by%20repeated%20concatenation%20will%20have%20a%20quadratic%20runtime%20cost ). You should append each chunk of text to a list and then `''.join(lst)` at the end.
___
*[`detection/component_util/mpf_component_util/audio_transcoder.py` line 130 at r2](https://reviewable.io/reviews/openmpf/openmpf-python-component-sdk/63#-N8xPWlUCopQHq-fCL6H:-N8xPWlUCopQHq-fCL6I:bdu54ev) ([raw file](https://github.com/openmpf/openmpf-python-component-sdk/blob/84a0e2fdc5e8c819c97ae9cf13ab0765db475883/detection/component_util/mpf_component_util/audio_transcoder.py#L130)):*
> ```Python
>             if lowpass is not None:
>                 filtergraph.append(f'lowpass=f={lowpass}')
>             complex_str += "[unf];[unf]" + ','.join(filtergraph)\
> ```

I don't think the trailing `\` should be here.

**Review by cdglasz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-python-component-sdk/63)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @brosenberg42 and @jrobble)

___
*[`detection/component_util/mpf_component_util/audio_transcoder.py` line 118 at r2](https://reviewable.io/reviews/openmpf/openmpf-python-component-sdk/63#-N8xQwNRDABovVjsxoFT:-NABJsE0Aa2m09R3ZSE7:b-896fix) ([raw file](https://github.com/openmpf/openmpf-python-component-sdk/blob/84a0e2fdc5e8c819c97ae9cf13ab0765db475883/detection/component_util/mpf_component_util/audio_transcoder.py#L118)):*
<details><summary><i>Previously, brosenberg42 wrote…</i></summary><blockquote>

Strings are immutable so doing the concatenation like this in a loop results in a quadratic runtime. ( https://docs.python.org/3/library/stdtypes.html#:~:text=building%20up%20a%20sequence%20by%20repeated%20concatenation%20will%20have%20a%20quadratic%20runtime%20cost ). You should append each chunk of text to a list and then `''.join(lst)` at the end.
</blockquote></details>

Done.
___
*[`detection/component_util/mpf_component_util/audio_transcoder.py` line 130 at r2](https://reviewable.io/reviews/openmpf/openmpf-python-component-sdk/63#-N8xPWlUCopQHq-fCL6H:-NABJt6UDm6jdZiZG-cZ:b-896fix) ([raw file](https://github.com/openmpf/openmpf-python-component-sdk/blob/84a0e2fdc5e8c819c97ae9cf13ab0765db475883/detection/component_util/mpf_component_util/audio_transcoder.py#L130)):*
<details><summary><i>Previously, brosenberg42 wrote…</i></summary><blockquote>

I don't think the trailing `\` should be here.
</blockquote></details>

Done.

**Review by brosenberg42 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-python-component-sdk/63)* status: 0 of 3 files reviewed, 3 unresolved discussions (waiting on @brosenberg42, @cdglasz, and @jrobble)

___
*[`detection/component_util/mpf_component_util/job_config.py` line 69 at r4](https://reviewable.io/reviews/openmpf/openmpf-python-component-sdk/63#-NApEpjJ1-r5zcLcfSeQ:-NApEpjJ1-r5zcLcfSeR:b-7osmpm) ([raw file](https://github.com/openmpf/openmpf-python-component-sdk/blob/128163ef45c7aadec3f2f6962fdede24e3119834/detection/component_util/mpf_component_util/job_config.py#L69)):*
> ```Python
>         )
> 
> class JobConfig(object):
> ```

Let's call this `TriggeredJobConfig` since the majority of components don't use the trigger and we don't want to give the impression that this class should be used for those components.

**Review by cdglasz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-python-component-sdk/63)* status: 0 of 3 files reviewed, 3 unresolved discussions (waiting on @brosenberg42 and @jrobble)

___
*[`detection/component_util/mpf_component_util/job_config.py` line 69 at r4](https://reviewable.io/reviews/openmpf/openmpf-python-component-sdk/63#-NApEpjJ1-r5zcLcfSeQ:-NC74b0Q2k2-T75O56ge:b-896fix) ([raw file](https://github.com/openmpf/openmpf-python-component-sdk/blob/128163ef45c7aadec3f2f6962fdede24e3119834/detection/component_util/mpf_component_util/job_config.py#L69)):*
<details><summary><i>Previously, brosenberg42 wrote…</i></summary><blockquote>

Let's call this `TriggeredJobConfig` since the majority of components don't use the trigger and we don't want to give the impression that this class should be used for those components.
</blockquote></details>

Done.

**Review by jrobble — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-python-component-sdk/63)* status: all files reviewed, 1 unresolved discussion (waiting on @cdglasz)

___
*[`detection/component_util/mpf_component_util/job_config.py` line 98 at r5](https://reviewable.io/reviews/openmpf/openmpf-python-component-sdk/63#-NCW7D-47eX-iOtaqnFJ:-NCW7D-50dK30DtKMa3j:b-3gds09) ([raw file](https://github.com/openmpf/openmpf-python-component-sdk/blob/591c2f2f50a41f55490299b6704ed41248d1d94a/detection/component_util/mpf_component_util/job_config.py#L98)):*
> ```Python
>         trigger = mpf_util.get_property(
>             properties=job.job_properties,
>             key='TRIGGER',
> ```

Not all feed-forward jobs will necessarily have a trigger. Specifically, feed-forward jobs for non-dynamic-speech pipelines will not. For example, let's say someone created a component that creates audio derivative media in the first stage, or runs a SCENE DETECTION --> AZURE SPEECH pipeline.

Similarly, not all feed-forward tracks may have `VOICED_SEGMENTS` defined since they won't be coming from the first stage in a dynamic speech pipeline that determines the speakers, languages, and segments.

Currently, your STT components log a message and return the feed-forward track unmodified when there is a TriggerMismatch exception. That should only happen if `TRIGGER` is defined as a job property and the trigger doesn't match. If it's not defined, then the components should process the job normally.

Disclaimer: I have not performed a live test of this yet, only a static code review.

**Review by cdglasz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-python-component-sdk/63)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @brosenberg42 and @jrobble)

___
*[`detection/component_util/mpf_component_util/job_config.py` line 98 at r5](https://reviewable.io/reviews/openmpf/openmpf-python-component-sdk/63#-NCW7D-47eX-iOtaqnFJ:-NEMP90w8WmQbtkxSluF:b-896fix) ([raw file](https://github.com/openmpf/openmpf-python-component-sdk/blob/591c2f2f50a41f55490299b6704ed41248d1d94a/detection/component_util/mpf_component_util/job_config.py#L98)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Not all feed-forward jobs will necessarily have a trigger. Specifically, feed-forward jobs for non-dynamic-speech pipelines will not. For example, let's say someone created a component that creates audio derivative media in the first stage, or runs a SCENE DETECTION --> AZURE SPEECH pipeline.

Similarly, not all feed-forward tracks may have `VOICED_SEGMENTS` defined since they won't be coming from the first stage in a dynamic speech pipeline that determines the speakers, languages, and segments.

Currently, your STT components log a message and return the feed-forward track unmodified when there is a TriggerMismatch exception. That should only happen if `TRIGGER` is defined as a job property and the trigger doesn't match. If it's not defined, then the components should process the job normally.

Disclaimer: I have not performed a live test of this yet, only a static code review.
</blockquote></details>

Done.

**Review by jrobble — CHANGES_REQUESTED** [review]
> Reviewed 1 of 3 files at r3, 1 of 2 files at r5, 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-python-component-sdk/63)* status: all files reviewed, 8 unresolved discussions (waiting on @cdglasz)

___
*[`detection/component_util/mpf_component_util/audio_transcoder.py` line 94 at r8](https://reviewable.io/reviews/openmpf/openmpf-python-component-sdk/63#-NL7jgGn9zL4-hkKIyCG:-NL7jgGn9zL4-hkKIyCH:b-ygruc0) ([raw file](https://github.com/openmpf/openmpf-python-component-sdk/blob/13c74958a8b732a869cd1599edbef53ca86a007c/detection/component_util/mpf_component_util/audio_transcoder.py#L94)):*
> ```Python
>     else:
>         # Construct complex filter to trim and concatenate audio
>         trim_str = []
> ```

Nitpick: I like your use of arrays, but calling these a `str` is a bit misleading. Please call them something else. The end result is a string, so that's fine.
___
*[`detection/component_util/mpf_component_util/job_config.py` line 64 at r8](https://reviewable.io/reviews/openmpf/openmpf-python-component-sdk/63#-NL7Al2P2nWmY3MZsGLo:-NL7Al2P2nWmY3MZsGLp:b-mjp5z7) ([raw file](https://github.com/openmpf/openmpf-python-component-sdk/blob/13c74958a8b732a869cd1599edbef53ca86a007c/detection/component_util/mpf_component_util/job_config.py#L64)):*
> ```Python
>     def __str__(self):
>         return (
>             f"All segments out-of-bounds ({self.n_early} segments before "
> ```

Add a period at the end of  "All segments out-of-bounds".
___
*[`detection/component_util/mpf_component_util/job_config.py` line 95 at r8](https://reviewable.io/reviews/openmpf/openmpf-python-component-sdk/63#-NL75xEp65ocv2JKXdXV:-NL75xEq9DtjgMmSPEql:b-h63esu) ([raw file](https://github.com/openmpf/openmpf-python-component-sdk/blob/13c74958a8b732a869cd1599edbef53ca86a007c/detection/component_util/mpf_component_util/job_config.py#L95)):*
> ```Python
> 
>     @staticmethod
>     def _check_trigger(job: Union[mpf.ImageJob, mpf.AudioJob, mpf.VideoJob, mpf.GenericJob]):
> ```

Can this just be `job: MpfJob`?
___
*[`detection/component_util/mpf_component_util/job_config.py` line 107 at r8](https://reviewable.io/reviews/openmpf/openmpf-python-component-sdk/63#-NL76xof0ix2-HNEDbpO:-NL76xof0ix2-HNEDbpP:b-8pqiqm) ([raw file](https://github.com/openmpf/openmpf-python-component-sdk/blob/13c74958a8b732a869cd1599edbef53ca86a007c/detection/component_util/mpf_component_util/job_config.py#L107)):*
> ```Python
> 
>         # If trigger key is in feed-forward properties, only run
>         #  transcription if the value matches trigger_val
> ```

Remove underscore in "trigger_val" here since that is not the name of the variable, but rather a description.
___
*[`detection/component_util/mpf_component_util/job_config.py` line 134 at r8](https://reviewable.io/reviews/openmpf/openmpf-python-component-sdk/63#-NL79hQg3s-IDRdOYaei:-NL79hQg3s-IDRdOYaej:bi3j92p) ([raw file](https://github.com/openmpf/openmpf-python-component-sdk/blob/13c74958a8b732a869cd1599edbef53ca86a007c/detection/component_util/mpf_component_util/job_config.py#L134)):*
> ```Python
>     :ivar fps: Frames per second for video jobs
>     :ivar speaker_id_prefix: Prefix for LONG_SPEAKER_ID
>     :ivar overwrite_ids: Whether this is probably a subjob
> ```

"probably" ?

I think it's better to say "Whether this has been identified as a subjob"
___
*[`detection/component_util/mpf_component_util/job_config.py` line 176 at r8](https://reviewable.io/reviews/openmpf/openmpf-python-component-sdk/63#-NL7Li538Vj7W5SYXtnQ:-NL7Li538Vj7W5SYXtnR:b-mc48zd) ([raw file](https://github.com/openmpf/openmpf-python-component-sdk/blob/13c74958a8b732a869cd1599edbef53ca86a007c/detection/component_util/mpf_component_util/job_config.py#L176)):*
> ```Python
>             media_frame_count = int(job.media_properties.get('FRAME_COUNT', -1))
> 
>             # Determine whether this may be a subjob, based on whether the
> ```

Note that users can specify one or more time ranges or frame ranges in a video job request. The WFM will effectively create one segment for each and process them as sub-jobs, but they won't necessarily be part of a feed-forward job.

Do you see any reason why this would cause a problem with your current implementation?
___
*[`detection/component_util/mpf_component_util/job_config.py` line 179 at r8](https://reviewable.io/reviews/openmpf/openmpf-python-component-sdk/63#-NL7QosY9kb3bYs3TVeg:-NL7QosY9kb3bYs3TVeh:b-rgliq4) ([raw file](https://github.com/openmpf/openmpf-python-component-sdk/blob/13c74958a8b732a869cd1599edbef53ca86a007c/detection/component_util/mpf_component_util/job_config.py#L179)):*
> ```Python
>             #  start and stop frames line up with the media length
>             if stop_frame is not None:
>                 if start_frame > 0:
> ```

Nitpick: These three conditions have the same result. It would be more logical to wrap each in parentheses and `or` them together (one condition per line). That will allow you to write `self.overwrite_ids = True` once.
___
*[`detection/component_util/mpf_component_util/job_config.py` line 211 at r8](https://reviewable.io/reviews/openmpf/openmpf-python-component-sdk/63#-NL7S5Eq09WYsJAsn-Ed:-NL7S5Eq09WYsJAsn-Ee:b-oel6ip) ([raw file](https://github.com/openmpf/openmpf-python-component-sdk/blob/13c74958a8b732a869cd1599edbef53ca86a007c/detection/component_util/mpf_component_util/job_config.py#L211)):*
> ```Python
>             #  start and stop frames line up with the media length
>             if self.stop_time is not None:
>                 if self.start_time > 0:
> ```

Nitpick: These two conditions have the same result. Refer to previous comment about using `or`.

**Review by cdglasz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-python-component-sdk/63)* status: 1 of 3 files reviewed, 8 unresolved discussions (waiting on @brosenberg42 and @jrobble)

___
*[`detection/component_util/mpf_component_util/audio_transcoder.py` line 94 at r8](https://reviewable.io/reviews/openmpf/openmpf-python-component-sdk/63#-NL7jgGn9zL4-hkKIyCG:-NLN-78oAmAHuPfDya0V:b-896fix) ([raw file](https://github.com/openmpf/openmpf-python-component-sdk/blob/13c74958a8b732a869cd1599edbef53ca86a007c/detection/component_util/mpf_component_util/audio_transcoder.py#L94)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Nitpick: I like your use of arrays, but calling these a `str` is a bit misleading. Please call them something else. The end result is a string, so that's fine.
</blockquote></details>

Done.
___
*[`detection/component_util/mpf_component_util/job_config.py` line 64 at r8](https://reviewable.io/reviews/openmpf/openmpf-python-component-sdk/63#-NL7Al2P2nWmY3MZsGLo:-NLN-E3t-Y-rG2UrP5oa:b9h9st0) ([raw file](https://github.com/openmpf/openmpf-python-component-sdk/blob/13c74958a8b732a869cd1599edbef53ca86a007c/detection/component_util/mpf_component_util/job_config.py#L64)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Add a period at the end of  "All segments out-of-bounds".
</blockquote></details>

Placed it after the parenthetical; message will read `All segments out-of-bounds (2 segments before job start time, 4 after job end time).`
___
*[`detection/component_util/mpf_component_util/job_config.py` line 95 at r8](https://reviewable.io/reviews/openmpf/openmpf-python-component-sdk/63#-NL75xEp65ocv2JKXdXV:-NLN-VgBBJ0u9icnrrNO:b-896fix) ([raw file](https://github.com/openmpf/openmpf-python-component-sdk/blob/13c74958a8b732a869cd1599edbef53ca86a007c/detection/component_util/mpf_component_util/job_config.py#L95)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Can this just be `job: MpfJob`?
</blockquote></details>

Done.
___
*[`detection/component_util/mpf_component_util/job_config.py` line 107 at r8](https://reviewable.io/reviews/openmpf/openmpf-python-component-sdk/63#-NL76xof0ix2-HNEDbpO:-NLN-WsGDvdVTRlkqJGV:b-896fix) ([raw file](https://github.com/openmpf/openmpf-python-component-sdk/blob/13c74958a8b732a869cd1599edbef53ca86a007c/detection/component_util/mpf_component_util/job_config.py#L107)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Remove underscore in "trigger_val" here since that is not the name of the variable, but rather a description.
</blockquote></details>

Done.
___
*[`detection/component_util/mpf_component_util/job_config.py` line 134 at r8](https://reviewable.io/reviews/openmpf/openmpf-python-component-sdk/63#-NL79hQg3s-IDRdOYaei:-NLMmwIK-QbOx1AoC5lR:b-7xirp4) ([raw file](https://github.com/openmpf/openmpf-python-component-sdk/blob/13c74958a8b732a869cd1599edbef53ca86a007c/detection/component_util/mpf_component_util/job_config.py#L134)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

"probably" ?

I think it's better to say "Whether this has been identified as a subjob"
</blockquote></details>

Changing to `Whether this has been identified as a likely subjob`. I think there ought to be uncertainty indicated, since it's not confirmed to be a subjob, we're just using some relatively reliable proxy information (the start and end times)
___
*[`detection/component_util/mpf_component_util/job_config.py` line 176 at r8](https://reviewable.io/reviews/openmpf/openmpf-python-component-sdk/63#-NL7Li538Vj7W5SYXtnQ:-NLMnKBH3Sr932s2cZiz:b8xglff) ([raw file](https://github.com/openmpf/openmpf-python-component-sdk/blob/13c74958a8b732a869cd1599edbef53ca86a007c/detection/component_util/mpf_component_util/job_config.py#L176)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Note that users can specify one or more time ranges or frame ranges in a video job request. The WFM will effectively create one segment for each and process them as sub-jobs, but they won't necessarily be part of a feed-forward job.

Do you see any reason why this would cause a problem with your current implementation?
</blockquote></details>

This doesn't have to do with whether things are part of a feed-forward job, just whether they're sub-jobs of a job that's been divided up by the WFM (and therefore speaker IDs need to be unique between them). 
___
*[`detection/component_util/mpf_component_util/job_config.py` line 179 at r8](https://reviewable.io/reviews/openmpf/openmpf-python-component-sdk/63#-NL7QosY9kb3bYs3TVeg:-NLN-Z4QEywmtRZ2wt7k:b-896fix) ([raw file](https://github.com/openmpf/openmpf-python-component-sdk/blob/13c74958a8b732a869cd1599edbef53ca86a007c/detection/component_util/mpf_component_util/job_config.py#L179)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Nitpick: These three conditions have the same result. It would be more logical to wrap each in parentheses and `or` them together (one condition per line). That will allow you to write `self.overwrite_ids = True` once.
</blockquote></details>

Done.
___
*[`detection/component_util/mpf_component_util/job_config.py` line 211 at r8](https://reviewable.io/reviews/openmpf/openmpf-python-component-sdk/63#-NL7S5Eq09WYsJAsn-Ed:-NLN-Zod4wQ7Wwmxn0NV:b-896fix) ([raw file](https://github.com/openmpf/openmpf-python-component-sdk/blob/13c74958a8b732a869cd1599edbef53ca86a007c/detection/component_util/mpf_component_util/job_config.py#L211)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Nitpick: These two conditions have the same result. Refer to previous comment about using `or`.
</blockquote></details>

Done.

**Review by jrobble — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-python-component-sdk/63)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @cdglasz)

___
*[`detection/component_util/mpf_component_util/job_config.py` line 176 at r8](https://reviewable.io/reviews/openmpf/openmpf-python-component-sdk/63#-NL7Li538Vj7W5SYXtnQ:-NLWvdmm27LmkSST03cu:b1zbhvv) ([raw file](https://github.com/openmpf/openmpf-python-component-sdk/blob/13c74958a8b732a869cd1599edbef53ca86a007c/detection/component_util/mpf_component_util/job_config.py#L176)):*
<details><summary><i>Previously, cdglasz (Christopher Glasz) wrote…</i></summary><blockquote>

This doesn't have to do with whether things are part of a feed-forward job, just whether they're sub-jobs of a job that's been divided up by the WFM (and therefore speaker IDs need to be unique between them). 
</blockquote></details>

I'm just thinking that sub-jobs that are a result of:

1. feed-forward 
2. segmenting long videos
3. user-specified ranges (for both audio and video jobs)

It seems that all of these would meet the conditions for setting `self.overwrite_ids = True`. I know you're well aware of 1 and 2. I wasn't sure if you've considered 3. While 2 and 3 are pretty much the same in regards to video jobs, the bigger difference is audio jobs since previously audio jobs could not be segmented.

I'm not sure if this changes anything. I just want to bring it to your attention in case you think it does.

**Review by jrobble — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-python-component-sdk/63)* status: 2 of 3 files reviewed, all discussions resolved (waiting on @cdglasz)

___
*[`detection/component_util/mpf_component_util/job_config.py` line 176 at r8](https://reviewable.io/reviews/openmpf/openmpf-python-component-sdk/63#-NL7Li538Vj7W5SYXtnQ:-NLWxIaE1TGq1vCFfeL2:b-ha0l9e) ([raw file](https://github.com/openmpf/openmpf-python-component-sdk/blob/13c74958a8b732a869cd1599edbef53ca86a007c/detection/component_util/mpf_component_util/job_config.py#L176)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

I'm just thinking that sub-jobs that are a result of:

1. feed-forward 
2. segmenting long videos
3. user-specified ranges (for both audio and video jobs)

It seems that all of these would meet the conditions for setting `self.overwrite_ids = True`. I know you're well aware of 1 and 2. I wasn't sure if you've considered 3. While 2 and 3 are pretty much the same in regards to video jobs, the bigger difference is audio jobs since previously audio jobs could not be segmented.

I'm not sure if this changes anything. I just want to bring it to your attention in case you think it does.
</blockquote></details>

Actually, scratch that. We only support user-specified ranges for video jobs.

**Review by jrobble — COMMENTED** [review]
> Reviewed 1 of 2 files at r9.
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-python-component-sdk/63)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @cdglasz)

**Review by jrobble — COMMENTED** [review]
> Reviewed 2 of 2 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-python-component-sdk/63)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @cdglasz)

**Pull request merged**
