### PR TITLE
Python __future__ imports

### PR DESCRIPTION
**Pull request by brosenberg42**
This change is [Reviewable](https://reviewable.io/reviews/openmpf/openmpf-python-component-sdk/6)

### CODE REVIEW

**Comment by jrobble** [comment]
Should I try to run this code with Python 3 to make sure it works? 

What was the command you used to generate documentation? Do I need to be in a certain directory?

---







*Comments from [Reviewable](https://reviewable.io/reviews/openmpf/openmpf-python-component-sdk/6#-:-LF0S6iX5wAms620a19M:b9d66s8)*

**Comment by brosenberg42** [comment]
Review status: 0 of 12 files reviewed, 2 unresolved discussions (waiting on @jrobble)

---

*[detection/component_util/mpf_component_util/frame_filters/frame_filter.py, line 127 at r2](https://reviewable.io/reviews/openmpf/openmpf-python-component-sdk/6#-LF3BVkNBdyiQ8djbmg8:-LF3BVkNBdyiQ8djbmg9:b-wv1a08) ([raw file](https://github.com/openmpf/openmpf-python-component-sdk/blob/712a8dd355dbd25dfe180c9f72bd09d2dfd3a40f/detection/component_util/mpf_component_util/frame_filters/frame_filter.py#L127)):*
> ```Python
>         """
>         segment_fps = self.get_segment_frame_rate(original_frame_rate)
>         return int(segment_fps * segment_milliseconds / 1000)
> ```

This returned the right value, but it was a float instead of int.

---

*[detection/component_util/tests/test_video_capture.py, line 247 at r2](https://reviewable.io/reviews/openmpf/openmpf-python-component-sdk/6#-LF3BLfi4Sytd7ylt_hy:-LF3BLfi4Sytd7ylt_hz:bupskox) ([raw file](https://github.com/openmpf/openmpf-python-component-sdk/blob/712a8dd355dbd25dfe180c9f72bd09d2dfd3a40f/detection/component_util/tests/test_video_capture.py#L247)):*
> ```Python
>         for frame_filter in get_filters(filter_args):
>             actual = frame_filter.millis_to_segment_frame_position(original_frame_rate, segment_millis)
>             self.assertIsInstance(actual, int)
> ```

This test passed before because `self.assertEqual(1, 1.0)` is True

---


*Comments from [Reviewable](https://reviewable.io/reviews/openmpf/openmpf-python-component-sdk/6)*

**Comment by jrobble** [comment]
Reviewed 10 of 12 files at r1, 2 of 2 files at r2.
Review status: all files reviewed, 4 unresolved discussions (waiting on @brosenberg42)

---

*[README.md, line 57 at r2](https://reviewable.io/reviews/openmpf/openmpf-python-component-sdk/6#-LF4AX3M2KxM-nc1KNLi:-LF4AX3M2KxM-nc1KNLj:b-3i8r6n) ([raw file](https://github.com/openmpf/openmpf-python-component-sdk/blob/712a8dd355dbd25dfe180c9f72bd09d2dfd3a40f/README.md#L57)):*
> ```Markdown
> 
> * If not already installed, install [pip](https://pip.pypa.io).
> * (Optional) If not already installed, install [virtualenv](http://virtualenv.pypa.io).
> ```

What is the advantage of using virtualenv here? Installing virtualenv is mentioned in the Build Guide, but not creating a virtualenv for the Python Component API. Please provide some motivation for the user, or remove this last step.

---

*[detection/component_util/mpf_component_util/utils.py, line 27 at r2](https://reviewable.io/reviews/openmpf/openmpf-python-component-sdk/6#-LF47BZ437qe9kbDI2BU:-LF47BZ437qe9kbDI2BV:b-8jlpt2) ([raw file](https://github.com/openmpf/openmpf-python-component-sdk/blob/712a8dd355dbd25dfe180c9f72bd09d2dfd3a40f/detection/component_util/mpf_component_util/utils.py#L27)):*
> ```Python
> #############################################################################
> 
> from __future__ import print_function
> ```

Do we want to put the following in every API .py file?

`from __future__ import division, print_function`

I'm thinking about the case where for some reason in the future we introduce a line of code that does division in a file which currently doesn't have that line. Then we start getting inconsistent behaviors between files which do and do not have it. Will we remember to add that line? Maybe not if everything seems like it's working.

---

*[detection/component_util/mpf_component_util/frame_filters/frame_filter.py, line 127 at r2](https://reviewable.io/reviews/openmpf/openmpf-python-component-sdk/6#-LF3BVkNBdyiQ8djbmg8:-LF46Fv41ynAyduuFTaP:b-8fx2u7) ([raw file](https://github.com/openmpf/openmpf-python-component-sdk/blob/712a8dd355dbd25dfe180c9f72bd09d2dfd3a40f/detection/component_util/mpf_component_util/frame_filters/frame_filter.py#L127)):*
<details><summary><i>Previously, brosenberg42 wrote…</i></summary><blockquote>

This returned the right value, but it was a float instead of int.
</blockquote></details>

:+1: 

---


*Comments from [Reviewable](https://reviewable.io/reviews/openmpf/openmpf-python-component-sdk/6)*

**Comment by jrobble** [comment]
Review status: all files reviewed, 5 unresolved discussions (waiting on @brosenberg42)

---

*[README.md, line 68 at r2](https://reviewable.io/reviews/openmpf/openmpf-python-component-sdk/6#-LF5Fp9h4p5WoTPoo_K6:-LF5Fp9i95MZEF1QcxMR:b-94e2zx) ([raw file](https://github.com/openmpf/openmpf-python-component-sdk/blob/712a8dd355dbd25dfe180c9f72bd09d2dfd3a40f/README.md#L68)):*
Please change this to:

> Please read the [Python Batch Component API documentation](https://openmpf.github.io/docs/site/Python-Batch-Component-API)
to get started.

---


*Comments from [Reviewable](https://reviewable.io/reviews/openmpf/openmpf-python-component-sdk/6)*

**Comment by jrobble** [comment]
Review status: all files reviewed, 6 unresolved discussions (waiting on @brosenberg42)

---

*[README.md, line 73 at r2](https://reviewable.io/reviews/openmpf/openmpf-python-component-sdk/6#-LF5I7imCOY6vAUtkJRR:-LF5I7imCOY6vAUtkJRS:b4t4za1) ([raw file](https://github.com/openmpf/openmpf-python-component-sdk/blob/712a8dd355dbd25dfe180c9f72bd09d2dfd3a40f/README.md#L73)):*
> ```Markdown
> ## Project Website
> 
> For more information about OpenMPF, including documentation, guides, and other material, visit our [website](https://openmpf.github.io/)
> ```

Add a period at the end here.

---


*Comments from [Reviewable](https://reviewable.io/reviews/openmpf/openmpf-python-component-sdk/6)*

**Comment by brosenberg42** [comment]
Review status: 1 of 22 files reviewed, 4 unresolved discussions (waiting on @jrobble)

---

*[README.md, line 57 at r2](https://reviewable.io/reviews/openmpf/openmpf-python-component-sdk/6#-LF4AX3M2KxM-nc1KNLi:-LFHzumBAgV6Gx-tGCQx:b-896fix) ([raw file](https://github.com/openmpf/openmpf-python-component-sdk/blob/712a8dd355dbd25dfe180c9f72bd09d2dfd3a40f/README.md#L57)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

What is the advantage of using virtualenv here? Installing virtualenv is mentioned in the Build Guide, but not creating a virtualenv for the Python Component API. Please provide some motivation for the user, or remove this last step.
</blockquote></details>

Done.

---

*[README.md, line 68 at r2](https://reviewable.io/reviews/openmpf/openmpf-python-component-sdk/6#-LF5Fp9h4p5WoTPoo_K6:-LFHzw2UCN60gSGRPB9_:b-896fix) ([raw file](https://github.com/openmpf/openmpf-python-component-sdk/blob/712a8dd355dbd25dfe180c9f72bd09d2dfd3a40f/README.md#L68)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Please change this to:

> Please read the [Python Batch Component API documentation](https://openmpf.github.io/docs/site/Python-Batch-Component-API)
to get started.
</blockquote></details>

Done.

---

*[README.md, line 73 at r2](https://reviewable.io/reviews/openmpf/openmpf-python-component-sdk/6#-LF5I7imCOY6vAUtkJRR:-LFHzwN7BWVliqfRL0qv:b-896fix) ([raw file](https://github.com/openmpf/openmpf-python-component-sdk/blob/712a8dd355dbd25dfe180c9f72bd09d2dfd3a40f/README.md#L73)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Add a period at the end here.
</blockquote></details>

Done.

---

*[detection/component_util/mpf_component_util/utils.py, line 27 at r2](https://reviewable.io/reviews/openmpf/openmpf-python-component-sdk/6#-LF47BZ437qe9kbDI2BU:-LFI--Y520JNld7wH1kp:b-896fix) ([raw file](https://github.com/openmpf/openmpf-python-component-sdk/blob/712a8dd355dbd25dfe180c9f72bd09d2dfd3a40f/detection/component_util/mpf_component_util/utils.py#L27)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Do we want to put the following in every API .py file?

`from __future__ import division, print_function`

I'm thinking about the case where for some reason in the future we introduce a line of code that does division in a file which currently doesn't have that line. Then we start getting inconsistent behaviors between files which do and do not have it. Will we remember to add that line? Maybe not if everything seems like it's working.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/openmpf/openmpf-python-component-sdk/6)*

**Comment by jrobble** [comment]
Reviewed 21 of 21 files at r3.
Review status: :shipit: complete! all files reviewed, all discussions resolved

---



*Comments from [Reviewable](https://reviewable.io/reviews/openmpf/openmpf-python-component-sdk/6)*

**Pull request merged**
