### PR TITLE
Add example Python component that uses setuptools and OpenCV

### PR DESCRIPTION
**Pull request by brosenberg42**
This change is [Reviewable](https://reviewable.io/reviews/openmpf/openmpf-python-component-sdk/3)

### CODE REVIEW

**Comment by jrobble** [comment]
I got this the first time I tried to build the SDK:

```
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] OpenMPF Java Component SDK ......................... SUCCESS [  0.332 s]
[INFO] OpenMPF Audio-Video Utils .......................... SUCCESS [  0.960 s]
[INFO] OpenMPF Java Component API ......................... SUCCESS [  2.536 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 3.973 s
[INFO] Finished at: 2018-05-18T14:30:34-04:00
[INFO] Final Memory: 20M/168M
[INFO] ------------------------------------------------------------------------
ERROR: 'pip wheel' requires the 'wheel' package. To fix this, run: pip install wheel
You are using pip version 8.1.2, however version 10.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
An error occurred while trying to build /home/mpf/git/openmpf-projects/openmpf-python-component-sdk/detection/api: Command '('pip', 'wheel', '--wheel-dir', '/home/mpf/mpf-sdk-install/python/wheelhouse', '/home/mpf/git/openmpf-projects/openmpf-python-component-sdk/detection/api')' returned non-zero exit status 1.
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] Media Processing Framework ......................... SUCCESS [  0.383 s]
[INFO] MPF Trunk Modules .................................. FAILURE [ 25.497 s]
[INFO] MPF Protocol Buffers ............................... SKIPPED
[INFO] MPF Interoperability Classes ....................... SKIPPED
[INFO] MPF Video Overlay .................................. SKIPPED
[INFO] MPF Markup Component ............................... SKIPPED
[INFO] MPF Node Manager ................................... SKIPPED
[INFO] MPF REST API ....................................... SKIPPED
[INFO] MPF REST Client .................................... SKIPPED
[INFO] MPF Java Component Executor ........................ SKIPPED
[INFO] MPF Install ........................................ SKIPPED
[INFO] MPF Java Test Components ........................... SKIPPED
[INFO] MPF Java Test Detection Component .................. SKIPPED
[INFO] MPF Workflow Manager ............................... SKIPPED
[INFO] MPF System Tests ................................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 26.175 s
[INFO] Finished at: 2018-05-18T14:30:35-04:00
[INFO] Final Memory: 18M/212M
[INFO] ------------------------------------------------------------------------
```

We've discussed this. See comments on https://github.com/openmpf/openmpf/pull/565.

---

Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[detection/examples/PythonOcvComponent/setup.py, line 1 at r1](https://reviewable.io/reviews/openmpf/openmpf-python-component-sdk/3#-LCnfJuvEV_spuPvqeHW:-LCnfJuw2358OCJequ1A:bzf1z1z) ([raw file](https://github.com/openmpf/openmpf-python-component-sdk/blob/b996038d953f01bfefcfd6fa931d0346e9253a39/detection/examples/PythonOcvComponent/setup.py#L1)):*
> ```Python
> import setuptools
> ```

Please add header comments.

---

*[detection/examples/PythonOcvComponent/ocv_component/ocv_component.py, line 1 at r1](https://reviewable.io/reviews/openmpf/openmpf-python-component-sdk/3#-LCnfPaB887p3Y07JjBh:-LCnfPaB887p3Y07JjBi:bzf1z1z) ([raw file](https://github.com/openmpf/openmpf-python-component-sdk/blob/b996038d953f01bfefcfd6fa931d0346e9253a39/detection/examples/PythonOcvComponent/ocv_component/ocv_component.py#L1)):*
> ```Python
> import cv2
> ```

Please add header comments.

---

*[detection/examples/PythonOcvComponent/ocv_component/ocv_component.py, line 1 at r1](https://reviewable.io/reviews/openmpf/openmpf-python-component-sdk/3#-LCoqpVZ3K80yx8g4xIq:-LCoqpVZ3K80yx8g4xIr:b-9k0asw) ([raw file](https://github.com/openmpf/openmpf-python-component-sdk/blob/b996038d953f01bfefcfd6fa931d0346e9253a39/detection/examples/PythonOcvComponent/ocv_component/ocv_component.py#L1)):*
> ```Python
> import cv2
> ```

Note to self: Test this.

---

*[detection/examples/PythonOcvComponent/ocv_component/ocv_component.py, line 9 at r1](https://reviewable.io/reviews/openmpf/openmpf-python-component-sdk/3#-LCnhHCY6M8ge7P1_g5-:-LCnhHCY6M8ge7P1_g50:b-9d8wp0) ([raw file](https://github.com/openmpf/openmpf-python-component-sdk/blob/b996038d953f01bfefcfd6fa931d0346e9253a39/detection/examples/PythonOcvComponent/ocv_component/ocv_component.py#L9)):*
> ```Python
> 
> class OcvComponent(object):
>     detection_type = 'PYTHON OCV TEST'
> ```

For your other test component, in test_component.py, you have:

```
detection_type = 'TEST DETECTION TYPE'
```

For consistency, let's make this type "TEST OCV DETECTION TYPE".

---


*Comments from [Reviewable](https://reviewable.io/reviews/openmpf/openmpf-python-component-sdk/3#-:-LCoWUjeEETxWjF0ym4F:b-1x8bbc)*

**Comment by brosenberg42** [comment]
Review status: 1 of 4 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[detection/examples/PythonOcvComponent/setup.py, line 1 at r1](https://reviewable.io/reviews/openmpf/openmpf-python-component-sdk/3#-LCnfJuvEV_spuPvqeHW:-LCpA3qpClwsy78D_d7Y:b-896fix) ([raw file](https://github.com/openmpf/openmpf-python-component-sdk/blob/b996038d953f01bfefcfd6fa931d0346e9253a39/detection/examples/PythonOcvComponent/setup.py#L1)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Please add header comments.
</blockquote></details>

Done.

---

*[detection/examples/PythonOcvComponent/ocv_component/ocv_component.py, line 1 at r1](https://reviewable.io/reviews/openmpf/openmpf-python-component-sdk/3#-LCnfPaB887p3Y07JjBh:-LCpA5GyDCJVtVij_Ya7:b-896fix) ([raw file](https://github.com/openmpf/openmpf-python-component-sdk/blob/b996038d953f01bfefcfd6fa931d0346e9253a39/detection/examples/PythonOcvComponent/ocv_component/ocv_component.py#L1)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Please add header comments.
</blockquote></details>

Done.

---

*[detection/examples/PythonOcvComponent/ocv_component/ocv_component.py, line 9 at r1](https://reviewable.io/reviews/openmpf/openmpf-python-component-sdk/3#-LCnhHCY6M8ge7P1_g5-:-LCpA6xPAT0Mx8W_jcAd:b-896fix) ([raw file](https://github.com/openmpf/openmpf-python-component-sdk/blob/b996038d953f01bfefcfd6fa931d0346e9253a39/detection/examples/PythonOcvComponent/ocv_component/ocv_component.py#L9)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

For your other test component, in test_component.py, you have:

```
detection_type = 'TEST DETECTION TYPE'
```

For consistency, let's make this type "TEST OCV DETECTION TYPE".
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/openmpf/openmpf-python-component-sdk/3)*

**Comment by jrobble** [comment]
Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io/reviews/openmpf/openmpf-python-component-sdk/3)*

**Comment by jrobble** [comment]
New component works as expected.

---

Review status: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---

*[detection/examples/PythonOcvComponent/plugin-files/descriptor/descriptor.json, line 17 at r2](https://reviewable.io/reviews/openmpf/openmpf-python-component-sdk/3#-LD2EmjgDVhf8ByC4snX:-LD2EmjgDVhf8ByC4snY:bvkug3u) ([raw file](https://github.com/openmpf/openmpf-python-component-sdk/blob/792d182e83e2790d6b17c93161a716ecadc2a30a/detection/examples/PythonOcvComponent/plugin-files/descriptor/descriptor.json#L17)):*
> ```JSON
>     "providesCollection" : {
>       "states" : [
>         "DETECTION"
> ```

For the other Python test component you have:

```
      "states" : [
        "DETECTION",
        "DETECTION_TestDetectionType",
        "DETECTION_TestDetectionType_PYTHONTEST"
      ],
```

You're missing the last two forms here.

---


*Comments from [Reviewable](https://reviewable.io/reviews/openmpf/openmpf-python-component-sdk/3#-:-LD2IQGb9H7EqAgaJV4s:bjnjp8u)*

**Comment by brosenberg42** [comment]
Review status: 3 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[detection/examples/PythonOcvComponent/plugin-files/descriptor/descriptor.json, line 17 at r2](https://reviewable.io/reviews/openmpf/openmpf-python-component-sdk/3#-LD2EmjgDVhf8ByC4snX:-LD2qEr6E0ME4ISZMSzp:b-896fix) ([raw file](https://github.com/openmpf/openmpf-python-component-sdk/blob/792d182e83e2790d6b17c93161a716ecadc2a30a/detection/examples/PythonOcvComponent/plugin-files/descriptor/descriptor.json#L17)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

For the other Python test component you have:

```
      "states" : [
        "DETECTION",
        "DETECTION_TestDetectionType",
        "DETECTION_TestDetectionType_PYTHONTEST"
      ],
```

You're missing the last two forms here.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/openmpf/openmpf-python-component-sdk/3)*

**Comment by jrobble** [comment]
Tested this via deployment upgrade. Works as expected.

---

Review status: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io/reviews/openmpf/openmpf-python-component-sdk/3#-:-LDo6kSb6a_H8RH6LGBb:bda89s3)*

**Pull request merged**
