### PR TITLE
Add nlp_text_splitter package

### PR DESCRIPTION
**Pull request by hhuangMITRE**
**Issues:**

- https://github.com/openmpf/openmpf/issues/1798

**Related PRs:**

- https://github.com/openmpf/openmpf-components/pull/364
- https://github.com/openmpf/openmpf-docker/pull/213

- - -
This change is [Reviewable](https://reviewable.io/reviews/openmpf/openmpf-python-component-sdk/78)

### CODE REVIEW

**Review by hhuangMITRE — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-python-component-sdk/78)* status: 5 of 9 files reviewed, 4 unresolved discussions (waiting on @brosenberg42 and @jrobble)

___
*[`detection/nlp_text_splitter/install.sh` line 1 at r2](https://reviewable.io/reviews/openmpf/openmpf-python-component-sdk/78#-NwpAq_Y04zWglzqvB7t:-Nwu1Hfu2deyXhoibmTL:bfjx4at) ([raw file](https://github.com/openmpf/openmpf-python-component-sdk/blob/41640ef18136c086c9bfeb687e60763e908ea7d2/detection/nlp_text_splitter/install.sh#L1)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Needs header comments.
</blockquote></details>

Fixed, thank you! I've updated the headers in this file to 2024. I can update the other headers from `2023->2024`  as well.
___
*[`detection/nlp_text_splitter/install.sh` line 7 at r2](https://reviewable.io/reviews/openmpf/openmpf-python-component-sdk/78#-NwpBVxpEj4TvkO_oJqO:-Nwu1N2lD4X86WIEUGFk:b-x510mv) ([raw file](https://github.com/openmpf/openmpf-python-component-sdk/blob/41640ef18136c086c9bfeb687e60763e908ea7d2/detection/nlp_text_splitter/install.sh#L7)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Should this be `--options t:gm:w:s:` ?

Specifically, the `b:` should be replaced with `s:` since that's the short version of `--install-spacy-model | -s`.
</blockquote></details>

Yes, it should be `s:` instead of `b:`. I fixed it, thanks!
___
*[`detection/nlp_text_splitter/install.sh` line 13 at r2](https://reviewable.io/reviews/openmpf/openmpf-python-component-sdk/78#-NwpCKsR-D6txs3wF4ms:-Nwu1iWZ5_V8mGToE7Ym:by31of9) ([raw file](https://github.com/openmpf/openmpf-python-component-sdk/blob/41640ef18136c086c9bfeb687e60763e908ea7d2/detection/nlp_text_splitter/install.sh#L13)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Call this `wtp_models_dir` for clarity.
</blockquote></details>

Done, I've also updated the function call `setup_wtp_models_dir`.
___
*[`detection/nlp_text_splitter/install.sh` line 130 at r2](https://reviewable.io/reviews/openmpf/openmpf-python-component-sdk/78#-NwpCUHG6vP0fyZLCfP8:-Nwu1kp58SmhYqrQ38yi:b-896fix) ([raw file](https://github.com/openmpf/openmpf-python-component-sdk/blob/41640ef18136c086c9bfeb687e60763e908ea7d2/detection/nlp_text_splitter/install.sh#L130)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Call this `--wtp-models-dir` for clarity. Update in the README as well.
</blockquote></details>

Done.
___
*[`detection/nlp_text_splitter/README.md` line 40 at r4](https://reviewable.io/reviews/openmpf/openmpf-python-component-sdk/78#-Nwu1omX9RYb-9OWa-d9:-Nwu1omX9RYb-9OWa-dA:b-fohfx5) ([raw file](https://github.com/openmpf/openmpf-python-component-sdk/blob/b0350fcade94d11e25c8c8503b11cce843e66c9f/detection/nlp_text_splitter/README.md#L40)):*
> ```Markdown
>   setup a PyTorch installation with CUDA (GPU) libraries.
> 
> - `--wtp-models-dir |-m <wtp-models-dir >`: Add this parameter to
> ```

Refactored to `wtp-models-dir`

**Comment by jrobble** [comment]
*[`detection/nlp_text_splitter/install.sh` line 34 at r5](https://reviewable.io/reviews/openmpf/openmpf-python-component-sdk/78#-Nx-OsfF28SH3Yrq4nQW:-Nx-OsfF28SH3Yrq4nQX:b-fs4hk5) ([raw file](https://github.com/openmpf/openmpf-python-component-sdk/blob/ea5e488c59d8f6204cf0b110392fa56e3dc31615/detection/nlp_text_splitter/install.sh#L34)):*
> ```Shell
>     if ! options=$(getopt --name "$0"  \
>             --options t:gm:w:s: \
>             --longoptions text-splitter-dir:,gpu,wtp-models-dir :,install-wtp-model:,install-spacy-model: \
> ```

This space before the colon made it so that I could not do a GPU build no matter when I provided for `BUILD_TYPE`: `wtp-models-dir :,install-wtp-model`

I fixed this in a commit.

**Comment by jrobble** [comment]
*[`detection/nlp_text_splitter/nlp_text_splitter/__init__.py` line 105 at r6](https://reviewable.io/reviews/openmpf/openmpf-python-component-sdk/78#-Nx0u1gr75MbOleCgzx-:-Nx0u1gs1hnjjBu1TiLD:b-eiv5wi) ([raw file](https://github.com/openmpf/openmpf-python-component-sdk/blob/220f3d0175bb40cefaf8a64458810b8fac3ded35/detection/nlp_text_splitter/nlp_text_splitter/__init__.py#L105)):*
> ```Python
>             self._default_lang = default_lang
> 
>         if self._model_name == wtp_model_name:
> ```

Not only do you need to check if the model name is the same, you need to also check if the model setting is the same (CPU vs. GPU).

I ran into a situation where on first run with `SENTENCE_MODEL_CPU_ONLY=false` the component was  `Using cached model: wtp-bert-mini` but I saw no GPU activity.

**Review by hhuangMITRE — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-python-component-sdk/78)* status: 4 of 9 files reviewed, 5 unresolved discussions (waiting on @brosenberg42 and @jrobble)

___
*[`detection/nlp_text_splitter/nlp_text_splitter/__init__.py` line 105 at r6](https://reviewable.io/reviews/openmpf/openmpf-python-component-sdk/78#-Nx0u1gr75MbOleCgzx-:-NxDrV6q8XO5Iah65BkR:b9gmtza) ([raw file](https://github.com/openmpf/openmpf-python-component-sdk/blob/220f3d0175bb40cefaf8a64458810b8fac3ded35/detection/nlp_text_splitter/nlp_text_splitter/__init__.py#L105)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Not only do you need to check if the model name is the same, you need to also check if the model setting is the same (CPU vs. GPU).

I ran into a situation where on first run with `SENTENCE_MODEL_CPU_ONLY=false` the component was  `Using cached model: wtp-bert-mini` but I saw no GPU activity.
</blockquote></details>

Thanks for catching that, I tested the `canine` series and didn't catch this. I've made the requested changes and rebuilt the images just to make sure. I've tested out the text-splitter with gpu servers: confirmed that the caching works when updating a cpu `wtp-bert-mini` to use `cuda/gpu`. 

Confirmed that works, bert-mini used about 800 MB of GPU memory.

**Review by jrobble — APPROVED** [review]
> Reviewed 3 of 4 files at r4, 1 of 1 files at r5, 1 of 1 files at r6, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-python-component-sdk/78)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @brosenberg42)

**Pull request merged**
